## Check Numpy version

In [245]:
import numpy as np
import pandas as pd

In [246]:
# jupyter nb print last one
print(pd.__version__)
print(np.__version__)

1.2.3
1.19.2


In [247]:
!pip list

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Package             Version
------------------- -----------
appdirs             1.4.4
configparser        4.0.2
contextlib2         0.6.0.post1
distlib             0.3.1
filelock            3.0.12
importlib-metadata  2.1.1
importlib-resources 3.3.1
pathlib2            2.3.5
pip                 20.3.4
pygame              2.0.1
scandir             1.10.0
setuptools          41.2.0
singledispatch      3.6.1
six                 1.15.0
typing              3.7.4.3
virtualenv          20.4.3
zipp                1.2.0


### create ndarray

In [248]:
arr = np.array([1,2,3,4],dtype=int)

In [249]:
type(arr)

numpy.ndarray

In [250]:
arr.shape

(4,)

In [251]:
arr

array([1, 2, 3, 4])

In [252]:
# python에서 list를 먼저 만들고, 이후에 np.arrary 로 타입 설정 해야 np에서 사용가능함
# shape 는 ndarray에서만 보이기 때문에 추후 주의 할 것

# 1차원 리스트
myList = [1,2,3,4]
# ndarray 로 전환시 소수점으로 변경
arr = np.array(myList,dtype=float)

In [253]:
arr

array([1., 2., 3., 4.])

In [254]:
# Quiz -> 소수를 정수로 전환할때는 그냥 버림 처리 되어버림
myList = [1.6, 2.6, 3.6, 4.6]
arr2 = np.array(myList,dtype=int)

In [255]:
arr2

array([1, 2, 3, 4])

In [256]:
# 2차원 리스트

myList2 = [[1,2,3,4],
           [5,6,7,8]]
myList3 = [[1.3,2,3,4],
           [5,6,7,8]]

In [257]:
myList2
myList3

[[1.3, 2, 3, 4], [5, 6, 7, 8]]

In [258]:
# ndarray 로 전환시 데이터 타입은 기존 속성을 따라감 (한개만 소수가 있으면 소수를 따라감)
arr = np.array(myList2)
arr3 = np.array(myList3)

In [259]:
print(arr)
print(arr.shape)
print(type(arr[0][0]))
print(arr3)
print(arr3.shape)
print(type(arr3[0][0]))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
<class 'numpy.int64'>
[[1.3 2.  3.  4. ]
 [5.  6.  7.  8. ]]
(2, 4)
<class 'numpy.float64'>


In [260]:
# 문자열이 포함될 경우 전체 문자열로 변경됨

myList = [1,3.14,"hello","1234"]

In [261]:
print(myList)
print(type(myList))

[1, 3.14, 'hello', '1234']
<class 'list'>


In [262]:
arr = np.array(myList)

In [263]:
arr

array(['1', '3.14', 'hello', '1234'], dtype='<U32')

In [264]:
# str add
print(arr[0]+arr[1])
# changed dtype 형변환
print(float(arr[0])+float(arr[1]))

13.14
4.140000000000001


### Slicing
#### selecting part of array

#### 1D array

In [265]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr.shape

(10,)

In [266]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [53]:
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

#### 2D array

In [55]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [56]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
# 한방에 할 수 있음
# arange (start_num, end_num, default strat_num=0)
arr2d = np.array(np.arange(1,13).reshape(3,4))

In [82]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
print(arr2d[0,2])
print(arr2d[2,2])

3
11


#### 1d slicing

In [97]:
arr1d = np.array(np.arange(1,13))

In [98]:
# 구간 추출 = 시작값(이상):종료값(미만)
# 시작값이 없으면 처음부터
# 종료값이 없으면 끝까지
print(arr1d[1:])
print(arr1d[1:10])
print(arr1d[:11])
print(arr1d[:-1])
print(arr1d[:-2])

[ 2  3  4  5  6  7  8  9 10 11 12]
[ 2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10]


#### 2d slicing

In [99]:
arr2d = np.array(np.arange(1,13).reshape(3,4))

In [100]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
# 특정 행 전체
# 행, 열(리스트 범위 재설정, : 전체)
print(arr2d[1])
print(arr2d[1,:])
print(arr2d[1,:].shape)

[5 6 7 8]
[5 6 7 8]
(4,)


In [114]:
# 행에 대해서 시작:종료, 열에 대해서 시작:종료로 복합적으로 사용

arr2d[:2,1:3]

array([[2, 3],
       [6, 7]])

In [161]:
# 5*5 배열, 11-36

my2dArr = np.array(np.arange(1,26).reshape(5,5))
print(my2dArr)
print(my2dArr[2:,1:4])
""

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14]
 [17 18 19]
 [22 23 24]]


''

### Fancy indexing
#### find out specific index value

In [123]:
# 1D fancy indexing
my1dArr = np.array(np.arange(1,10))

In [124]:
my1dArr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
idx = [0, 2, 4]
arr1d[idx]

array([1, 3, 5])

In [128]:
# 2D fancy indexing
my2dArr = np.array(np.arange(1,13).reshape(3,4))

In [129]:
my2dArr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
# 연속적이지 않은 값을 추출 할때 적합함
idx = [0,2,3]
print(my2dArr[:2,idx])


[[1 3 4]
 [5 7 8]]
[[1 2 3]
 [5 6 7]]


### Boolean indexing
#### using bool condition, find out what need

In [134]:
arr = np.array(np.arange(1,8))

In [135]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [136]:
arr2d = np.array(np.arange(1,13).reshape(3,4))

In [153]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
# True 값이 있는 경우는 해당 인덱스의 값은 추출함
myTureFalse = [True, False, True, False, False, False, False]

In [140]:
arr[myTureFalse]

array([1, 3])

In [155]:
myTureFalse2d = [[True, False, True, False],[True, False, True, False],[False, False, False, False]]
test2d = np.array(myTureFalse2d)

In [157]:
# arr2d[myTureFalse2d]
arr2d[test2d]

array([1, 3, 5, 7])

### Condition filter (<, >, =, <=, =>)

In [150]:
condi = arr2d > 2

In [151]:
arr2d[condi]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [158]:
# 조건필터의 값을 바로 인덱스에 바로 넣어도 됨 (객체화)
arr2d[arr2d > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [160]:
arr2d[arr2d < 5].reshape(2,-1)

array([[1, 2],
       [3, 4]])

## Arange?
### = array + range

In [ ]:
arr = [1,2,3,4,5,6,7,8,9,10]

In [162]:
# arange (start, stop, default strat_num=0)
# start = include index
# stop = exclude index

arr = np.arange(stop=11, start=1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [164]:
# make odd num ndarray
# arange(start, stop, step)
# 매개변수를 name으로 명시하는 경우는 순서를 임의로 하고자 할때
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

### range = in python grammar

In [170]:
# when define range, it has not made values yet.
# It really makes values in for or while method.
test = range(1,11)
test2 = range(1,11,2)
print(test)

range(1, 11)


In [171]:
for i in test :
    print(i)

1
2
3
4
5
6
7
8
9
10


In [172]:
for i in test2 : 
    print(i)

1
3
5
7
9


## ndArray sorting
### 1d sorting

In [173]:
arr = np.array([1,10,5,8,2,4,3,6,7,9])

In [181]:
# asc
mySort_asc = np.sort(arr)

In [182]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [183]:
mySort_asc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [184]:
# desc 
mySort_desc = np.sort(arr)[::-1]

In [185]:
mySort_desc

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 2d sorting

In [186]:
arr2d = np.array([[5,6,7,8],[4,3,2,1],[10,9,12,11]])

In [187]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [191]:
# axis 값으로 행(1), 열(0)에 대해서 구분됨
# 행 : 행 안에서 정렬
# 열 : 열 안에서 정렬
print(arr2d)
print(np.sort(arr2d, axis=1))
print(np.sort(arr2d, axis=0))
print(np.sort(arr2d, axis=1)[::-1])
print(np.sort(arr2d, axis=0)[::-1])

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]
[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[10  9 12 11]
 [ 5  6  7  8]
 [ 4  3  2  1]]


### argsort -> return index

In [193]:
arr2d = np.array([[5,6,7,8],[4,3,2,1],[10,9,12,11]])

In [194]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [195]:
# 행/열 정렬에 대한 인덱스 값을 리턴 해줌
np.argsort(arr2d,axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

## Calculate by numpy
### matrix plus / minus

In [198]:
# 덧셈
a = np.array([[1,2,3],
            [2,3,4]])

In [199]:
b = np.array([[3,4,5],
            [3,5,7]])

In [200]:
a+b

array([[ 4,  6,  8],
       [ 5,  8, 11]])

In [203]:
a = np.array([[1,2,3],
            [2,3,4]])

In [204]:
b = np.array([[1,2],
            [3,4],
            [5,6]])

In [205]:
# matrix shape error
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [206]:
# np.sum
a = np.array(np.arange(1,26).reshape(5,5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [207]:
# 같은 행(가로) 다 더함
print(np.sum(a, axis=1))
# 같은 열(세로) 다 더함
print(np.sum(a, axis=0))

[55 60 65 70 75]
[ 15  40  65  90 115]


### matrix multiple

In [213]:
a = np.array([[1,2,3],
            [2,3,4]])

In [214]:
b = np.array([[3,4,5],
            [3,5,7]])

In [215]:
a.shape, b.shape

((2, 3), (2, 3))

In [216]:
# shape 가 같은 경우
# 같은 위치의 값을 곱함
# Hadamard multiple
a*b

array([[ 3,  8, 15],
       [ 6, 15, 28]])

In [217]:
# shape 가 다른경우
a = np.array(np.arange(1,10).reshape(3,3))
b = np.array(np.arange(1,7).reshape(3,2))

In [219]:
a.shape, b.shape

((3, 3), (3, 2))

In [220]:
# define way 1
np.dot(a,b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [221]:
# define way 2
a.dot(b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

## Broadcasting

In [228]:
a = np.array([[1,2,3],
            [2,3,4]])

In [229]:
b = np.array([[3,3,3],
            [3,3,3]])

In [230]:
a+b

array([[4, 5, 6],
       [5, 6, 7]])

In [231]:
a+3

array([[4, 5, 6],
       [5, 6, 7]])

In [232]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

In [238]:
a = np.array([[1,2,3],
            [2,3,4]])

In [239]:
b = np.array([[1],
            [2]])

In [240]:
a.shape, b.shape

((2, 3), (2, 1))

In [241]:
# for each low calculate by broadcating
a*b

array([[1, 2, 3],
       [4, 6, 8]])

In [242]:
a = np.array([[1,2,3],
            [2,3,4]])

In [243]:
b = np.array([1,2,3])

In [244]:
# for each column calculate by broadcating
a*b

array([[ 1,  4,  9],
       [ 2,  6, 12]])